# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0002_remove_blogpost_allow_comments'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE INDEX blogposts_blogpost_ts_idx ON blogposts_blogpost USING gin(to_tsvector('english', title || ' ' || description || ' ' || content));",
            "DROP INDEX IF EXISTS items_item_name_ts_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX blogposts_comment_ts_idx ON blogposts_comment USING gin(to_tsvector('english', content));",
            "DROP INDEX IF EXISTS items_part_name_ts_idx;"
        ),
    ]
